import type { Metadata } from "next";
import Image from "next/image";
import esgLogo from "@/assets/esg-logo.jpeg";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body className={inter.className}>
        <div className="p-4">
          <header className="flex justify-center">
            <div className="flex items-center max-w-md w-full">
              <Image
                src={esgLogo}
                alt={"ESG Logo"}
                height={96}
              />
              <div className="text-2xl sm:text-3xl font-bold ml-6">
                ESG Geburtstage
              </div>
            </div>
          </header>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
